### PR TITLE
Create sarah_meister.txt

### PR DESCRIPTION
**Pull request by thesarahmeister**

### CODE REVIEW

**Comment by QuLogic** [comment]
@thesarahmeister You need to open the PR against the main repo, not your own!

**Comment by thesarahmeister** [comment]
how do i do that

**Comment by QuLogic** [comment]
Go to the [overview](https://github.com/thesarahmeister/training-prep-2015-09) and click the green button on the left of the branch name. Make sure the base fork is `swcarpentry/training-prep-2015-09` and head fork is `thesarahmeister/training-prep-2015-09` and the branch is `sarah_meister_bio`; then click Create Pull Request.

**Comment by thesarahmeister** [comment]
ah got it thanks!

**Pull request merged**
